# GitHub Pages configuration for League of Legends ML Project
title: "League of Legends ML Project"
description: "An end-to-end machine learning showcase demonstrating the complete ML lifecycle"
url: "https://ignacio-ireta.github.io"
baseurl: ""

# Build settings
source: docs
destination: _site

# Exclude files
exclude:
  - README.md
  - .gitignore
  - dragontail_source_data/
  - datascience_project/
  - test/

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections (if needed for future content)
collections_dir: docs

# SEO and social
author: "Ignacio Ireta"
twitter_username: ""
github_username: "ignacio-ireta"

# Custom variables
google_analytics: ""