// Offline internal-link checker: parses our authored HTML and verifies every
// relative href/src resolves to a file (or a directory with an index.html) on
// disk. External links (http(s)/mailto/tel) and in-page #anchors are skipped so
// the check stays deterministic and network-free. Exits non-zero on any break.
import { readFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Authored pages only. projects/cdmx-map/index.html is generated by Vite.
const pages = [
  "index.html",
  "projects/etf-portfolio-research/index.html",
  "reed/privacy/index.html"
];

function isExternal(url) {
  return /^[a-z][a-z0-9+.-]*:/i.test(url) || url.startsWith("//") || url.startsWith("#");
}

function stripQueryHash(url) {
  return url.replace(/[?#].*$/, "");
}

function targetExists(absPath) {
  if (!existsSync(absPath)) return false;
  return statSync(absPath).isDirectory() ? existsSync(join(absPath, "index.html")) : true;
}

let broken = 0;
let checked = 0;

for (const page of pages) {
  const pagePath = join(repoRoot, page);
  if (!existsSync(pagePath)) {
    console.error(`MISSING PAGE: ${page}`);
    broken += 1;
    continue;
  }
  const html = await readFile(pagePath, "utf8");
  const { document } = new JSDOM(html).window;
  const refs = [...document.querySelectorAll("[href]"), ...document.querySelectorAll("[src]")];
  for (const el of refs) {
    const raw = el.getAttribute("href") ?? el.getAttribute("src");
    if (!raw || isExternal(raw)) continue;
    const cleaned = stripQueryHash(raw);
    if (!cleaned) continue;
    const absPath = resolve(dirname(pagePath), cleaned);
    checked += 1;
    if (!targetExists(absPath)) {
      console.error(`BROKEN LINK in ${page}: "${raw}"`);
      broken += 1;
    }
  }
}

if (broken > 0) {
  console.error(`\n✖ ${broken} broken internal link(s) across ${pages.length} page(s).`);
  process.exit(1);
}
console.log(`✓ ${checked} internal link(s) OK across ${pages.length} page(s).`);
